name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      image_sha:
        description: 'Sha tag of the Docker image that was built'
        value: ${{ jobs.Build.outputs.image_sha }}

jobs:
  Build:
    name: Build & Deploy Image
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.sha_tag.outputs.full_image }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/prod-wm-api
          tags: |
            type=raw,value=${{ inputs.branch == 'main' && 'latest' || 'dev' }}
            type=sha,prefix=${{ inputs.branch }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: './apps/api/api.Dockerfile'
          platforms: linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Extract SHA tag
        id: sha_tag
        run: |
          FULL_IMAGE=$(echo "${{ steps.meta.outputs.tags }}" | grep "sha-" | head -n 1)
          echo "full_image=$FULL_IMAGE" >> $GITHUB_OUTPUT
