name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'dev'
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
    permissions:
      contents: read
      packages: write
