name: Deploy to Staging

on:
  pull_request:
    types: [opened, synchronize, labeled]
    paths:
      - 'apps/api/**'
  push:
    paths:
      - 'apps/api/**'
    branches-ignore:
      - 'main'

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      has-label: ${{ steps.check-label.outputs.has_label }}
    steps:
      - name: Check Associated PR Label
        id: check-label
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For PR events, check the current PR
            HAS_LABEL=$(jq 'any(.labels[]; .name == "deploy-dev")' <<< '${{ toJSON(github.event.pull_request) }}')
          else
            # For push events, find associated PR and check its labels
            PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
            HAS_LABEL=$(echo "$PR_DATA" | jq 'any(.[].labels[]; .name == "deploy-dev")')
          fi
          echo "has_label=$HAS_LABEL" >> $GITHUB_OUTPUT

  deploy:
    needs: check-pr
    if: needs.check-pr.outputs.has-label == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Staging
        run: echo "Deploying changes in 'apps/api/**' to staging."