name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'dev'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
    permissions:
      contents: read
      packages: write

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: echo "Deploying image tagged as 'dev' to staging environment."
