name: Deploy to Staging

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'apps/api/**'
  pull_request:
    types:
      - labeled
    branches-ignore:
      - main

jobs:
  build:
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy-dev'))
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: echo "Deploying image tagged as 'dev' to staging environment."
