name: Deploy to Staging

on:
  pull_request:
    types:
      - labeled
      - synchronize
    branches-ignore:
      - main

  push:
    branches:
      - '*'
    paths:
      - 'apps/api/**'
    branches-ignore:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label "deploy-dev" exists
        id: check_label
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Checking for label 'deploy-dev'..."
            labels=$(jq -r '.pull_request.labels[].name' <<<"${{ toJSON(github.event) }}")
            if [[ ! "$labels" =~ "deploy-dev" ]]; then
              echo "Label 'deploy-dev' is missing. Skipping deployment."
              exit 1
            fi
            echo "Label 'deploy-dev' is present."
          fi

      - name: Check for changes in 'apps/api/**'
        id: check_paths
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Checking for changes in 'apps/api/**'..."
            git fetch --depth=2
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
            if ! echo "$changes" | grep -q '^apps/api/'; then
              echo "No changes detected in 'apps/api/**'. Skipping deployment."
              exit 1
            fi
            echo "Relevant changes detected in 'apps/api/**'."
          fi

      - name: Deploy to Staging
        if: ${{ success() }}
        run: echo "Deploying changes in 'apps/api/**' with label 'deploy-dev' to staging."
